version: '3.7'

services:
          
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${PWD}/my-db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mysql

networks:     
  mysql:
    driver: bridge
    name: mysql_network